code --install-extension aki77.rails-partial
code --install-extension aki77.rails-routes
code --install-extension bung87.rails
code --install-extension bung87.vscode-gemfile
code --install-extension CraigMaslowski.erb
code --install-extension Equinusocio.vsc-material-theme
code --install-extension faustinoaq.crystal-lang
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GrapeCity.gc-excelviewer
code --install-extension HookyQR.beautify
code --install-extension karunamurti.haml
code --install-extension Kasik96.swift
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension mjmcloug.vscode-elixir
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.sublime-keybindings
code --install-extension PeterJausovec.vscode-docker
code --install-extension rebornix.ruby
code --install-extension richie5um2.vscode-sort-json
code --install-extension robertohuertasm.vscode-icons
code --install-extension robinbentley.sass-indented
code --install-extension shanehofstetter.rails-i18n
code --install-extension shanoor.vscode-nginx
code --install-extension sianglim.slim
code --install-extension sporto.rails-go-to-spec
code --install-extension timonwong.shellcheck
code --install-extension vincaslt.highlight-matching-tag
code --install-extension WakaTime.vscode-wakatime
code --install-extension wayou.vscode-todo-highlight
